set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Switch panes with prefix + h/j/k/l
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Open new pane (vertical split) with prefix + \
bind \\ split-window -h -c "#{pane_current_path}"
bind g display-popup -d "#{pane_current_path}" -w 80% -h 80% -E lazygit

# Resize panes with prefix + arrow keys, repeatable
bind -r Left resize-pane -L 5
bind -r Down resize-pane -D 5
bind -r Up resize-pane -U 5
bind -r Right resize-pane -R 5

# mouse and copy
set -g mouse on
setw -g mode-keys vi # trigger with prefix + [

# window and pane numbering to start at 1 instead of 0
set -g status-justify left
set -g base-index 1
setw -g pane-base-index 1

# status line theme and widgets
set -g @tokyo-night-tmux_transparent 1
set -g @tokyo-night-tmux_show_git 1
set -g @tokyo-night-tmux_show_netspeed 0
set -g @tokyo-night-tmux_show_wbg 1
set -g @tokyo-night-tmux_show_music 1
set -g @tokyo-night-tmux_show_path 1
run-shell "/opt/homebrew/bin/bash ~/.config/tmux/plugins/tokyo-night-tmux/tokyo-night.tmux"
set -g focus-events on
set -g status-left-length 99
set -g status-right-length 99

# reload tmux config
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display "reloaded tmux config!"
